# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
development:
  adapter: mysql2
  database: spud_cms_development
  username: root
  
test:
  adapter: mysql2
  database: spud_cms_test
  username: root

